version: '2'
services:
  ffmpeg-service:
    build: ./services/ffmpeg
    volumes:
     - ./services/ffmpeg:/service
     - ./node_modules:/service/node_modules
  extract-meta-data:
    build: ./services/extract-meta-data
    depends_on:
      - ffmpeg-service
    ports:
      - 8081:80
    volumes:
     - ./services/extract-meta-data:/service
     - ./node_modules:/service/node_modules
  http:
    image: httpd
    ports:
      - 8080:80
    volumes:
      - ./services/static-server:/usr/local/apache2/htdocs/
